#!/bin/bash
set -e

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution bookworm \
  --linux-flavours amd64 \
  --debian-installer live \
  --debian-installer-gui false \
  --binary-images iso-hybrid \
  --apt-indices false \
  --memtest none \
  --iso-application "Ayuchan Linux Live" \
  --iso-preparer "ayuchan" \
  --iso-publisher "ayuchan" \
  --iso-volume "AYUCHAN" \
  --win32-loader false \
  --bootappend-live "boot=live components username=ayuchan locales=zh_CN.UTF-8 keyboard-layouts=us i915.enable_psr=0 i915.enable_fbc=0 findiso=AYUCHAN live-delay=10 nosplash" \
  --bootappend-live-failsafe "boot=live components username=ayuchan nomodeset i915.enable_psr=0 findiso=AYUCHAN live-delay=15 debug nosplash" \
  --bootappend-install "priority=low i915.enable_psr=0 live-delay=10" \
  --archive-areas "main contrib non-free non-free-firmware"
