#!/bin/bash
set -e

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution bookworm \
  --linux-flavours amd64 \
  --debian-installer false \
  --binary-images iso-hybrid \
  --apt-indices false \
  --memtest none \
  --iso-application "Ayuchan Linux Live" \
  --iso-preparer "ayuchan" \
  --iso-publisher "ayuchan" \
  --iso-volume "AYUCHAN" \
  --win32-loader false \
  --bootappend-live "boot=live components username=ayuchan nomodeset i915.enable_psr=0 i915.enable_fbc=0 live-delay=5 nosplash" \
  --bootappend-live-failsafe "boot=live components username=ayuchan nomodeset i915.enable_psr=0 live-delay=10 debug nosplash" \
  --archive-areas "main contrib non-free non-free-firmware"
