[General]
type=image
background=/usr/share/wallpapers/Ayuchan/contents/images/ayuchan.svg
font=Noto Sans CJK SC, Noto Sans, sans-serif

[Wayland]
EnableAvatars=false
GreeterEnvironment=QT_IM_MODULE=fcitx
