---
# 根据 packagechooser 选择，在目标系统 chroot 中应用安装方案
dontChroot: false
timeout: 1800

packagechooser_packagechooser:
  full: "/usr/local/bin/ayuchan-apply-install-profile full"
  minimal: "/usr/local/bin/ayuchan-apply-install-profile minimal"
  dev: "/usr/local/bin/ayuchan-apply-install-profile dev"
  office: "/usr/local/bin/ayuchan-apply-install-profile office"
  "no-desktop": "/usr/local/bin/ayuchan-apply-install-profile no-desktop"
  "": "/usr/local/bin/ayuchan-apply-install-profile full"
  "*": "/usr/local/bin/ayuchan-apply-install-profile full"
