---
# 根据用户在 packagechooser 中的选择，在目标系统上安装/卸载组件
dontChroot: false
timeout: 1800

i18n:
  name: "Applying installation profile"
  name[zh_CN]: "正在应用安装方案"

packagechooser_packagechooser:
  full:
    - command: "/usr/local/bin/ayuchan-apply-install-profile full"
      timeout: 1800
      verbose: true
  minimal:
    - command: "/usr/local/bin/ayuchan-apply-install-profile minimal"
      timeout: 1200
      verbose: true
  dev:
    - command: "/usr/local/bin/ayuchan-apply-install-profile dev"
      timeout: 1800
      verbose: true
  office:
    - command: "/usr/local/bin/ayuchan-apply-install-profile office"
      timeout: 1800
      verbose: true
  no-desktop:
    - command: "/usr/local/bin/ayuchan-apply-install-profile no-desktop"
      timeout: 1200
      verbose: true
  "":
    - command: "/usr/local/bin/ayuchan-apply-install-profile full"
      timeout: 1800
      verbose: true
  "*":
    - command: "/usr/local/bin/ayuchan-apply-install-profile full"
      timeout: 1800
      verbose: true
