---
# Calamares 从 Live squashfs 解包（兼容多种 Live 路径）
unpack:
    - source: "/run/live/medium/live/filesystem.squashfs"
      sourcefs: "squashfs"
      destination: ""
    - source: "/lib/live/mount/medium/live/filesystem.squashfs"
      sourcefs: "squashfs"
      destination: ""
