---
# Ayuchan Linux Calamares 配置
# module-config: debian 提供各模块 .conf；sequence 必须在此定义

modules-search: [ /etc/calamares/modules, /usr/lib/calamares/modules ]

instance: debian

branding: ayuchan

prompt-install: true
dont-chroot: false

disable-cancel: false
disable-cancel-during-exec: true

show-shell-checks: true
requirements:
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - power
        - root
        - screen
    optional:
        - internet

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - packagechooser
        - users
        - summary
    - exec:
        - partition
        - mount
        - unpackfs
        - machineid
        - fstab
        - locale
        - keyboard
        - localecfg
        - users
        - displaymanager
        - contextualprocess
        - networkcfg
        - hwclock
        - services-systemd
        - bootloader
        - grubcfg
        - initramfs
        - removeuser
        - preservefiles
    - show:
        - finished

module-config: debian
